version: '3.4'
 
networks:
    gamedream:    
        driver: bridge  

volumes:
    db-data:
 
services:
    db:
        image: mcr.microsoft.com/mssql/server:2019-CU21-ubuntu-20.04
        restart: always
        ports:
            - 8107:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=d
        networks:
            - gamedream
        volumes:
            - db-data:/var/opt/mssql    
    api:
        restart: unless-stopped 
        ports:
            - 7018:80 
        build:
          context: .
          dockerfile: API/Dockerfile
        depends_on:
            - db
        networks:
            - gamedream
        volumes:
            - ./API/Logs:/app/Logs