name: Build and deploy ASP.Net Core app to Azure Web App - GamedreamAPIpro

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release GamedreamAPI.sln

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp GamedreamAPI.sln

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_19EC858A66774D2E98B9E91575639E1A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EE4D998AC02949FBAF5BC440DFC8F11F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2F773ECF48C64669858C4D6AE758F628 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'GamedreamAPIpro'
          slot-name: 'Production'
          package: .

      - name: Apply database migrations
        run: dotnet ef database update --context GamedreamContext --connection "Server=tcp:gamedreamsql.database.windows.net,1433;Database=gamedreamAPI;Uid=albertorbd;Pwd=saltamontes@02-10-1996;TrustServerCertificate=True;"
